### ISSUE TITLE
Unable to connect with firmware 16.10 on PowerShell 5.0

### ISSUE THREAD

**Issue by wybaux** [PowerAruba/PowerArubaSW#117]
Hi, 

When I try to connect to different switches on firmware 16.10.0010 It's not working as expected. It's fully working on switches using older firmware than 16.10

I try the following lines: 
```
$mysecpassword = ConvertTo-SecureString XXXX -AsPlainText -Force
Connect-ArubaSW  XXXXX -httpOnly -Username XXXX -Password $mysecpassword
``` 

I get the following error message 

```
Unable to connect

On character XXXXXXXXXX\Public\Connection.ps1:142  :13

Throw "Unable to connect"

+CategoryInfo: Operation Stopped: (Unable to connect: String) [], RuntimeException

+FullyQualifiedErrorId: Unable to connect)
```

Regards,

Nicolas

**Comment by alagoutte** [comment]
Hi Nicolas,

Thanks for report, i get the same issue with PowerShell 5.0 (work with PowerShell 7.0) but look a Aruba Switch bug...
i will make more check and test

**Comment by alagoutte** [comment]
After some test, working with 16.10.0007 (but fail with 10.16.0009 or 16.10.0010)

**Comment by alagoutte** [comment]
Hi Nicolas,

Get some news, the bug is known by Aruba and i hope it will be fixed on next firmware release...

**Comment by alagoutte** [comment]
Hello,

It is normally fix with 16.10.0011, can you try ?

**Comment by wybaux** [comment]
Hi, 

It's working !! 
The only think not working is "Connect-ArubaSW -httpOnly". Maybe a restriction in the new firmware. 
But when enabling https and running the script with SSL enable it's fully working.

**Comment by alagoutte** [comment]
> Hi,
> 
> It's working !!
> The only think not working is "Connect-ArubaSW -httpOnly". Maybe a restriction in the new firmware.
> But when enabling https and running the script with SSL enable it's fully working.

http work for me too (do you have check if you don't have disable http on the switch ?) it is a good idea of don't use http ;-)
