### ISSUE TITLE
Unable connect 

### ISSUE THREAD

**Issue by OregonWiseguy** [PowerAruba/PowerArubaSW#118]
When I try to make the initial connection I am getting a simple 'Unable to connect' error on multiple switches

Code tried

Connect-ArubaSW 10.35.97.43
Connect-ArubaSW 10.35.97.49 -SkipCertificateCheck
Connect-ArubaSW -httpOnly 10.35.97.49 -SkipCertificateCheck

Error tossed 
Unable to connect
At \\leg\is\home\StrawG\WindowsPowerShell\Modules\PowerArubaSW\0.8.0\Public\Connection.ps1:142 char:13
+             throw "Unable to connect"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to connect:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to connect

Version:
ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Script     0.8.0      PowerArubaSW                        {Add-ArubaSWLACP, Add-ArubaSWTrunk, Add-ArubaSWVlans, Add-ArubaSWVlansPorts...}                                

Settings:

 Web Management - Server Configuration

  HTTP Access    : Enabled
  HTTPS Access   : Enabled
  SSL Port       : 443
  Idle Timeout   : 600 seconds
  Management URL : http://h17007.www1.hpe.com/device_help
  Support URL    : http://www.arubanetworks.com/products/networking/
  User Interface : Improved
  Listen Mode    : data

**Comment by alagoutte** [comment]
Hello,

What firmware version ? If it is last 16.10, there is a bug on firmware, need to use PS7 or downgrade

**Comment by OregonWiseguy** [comment]
Upgrade to PS 7 did the trick due to the BUG in the 16.xx firmware
