### ISSUE TITLE
Get-ArubaSWPoe doesn't have -connection

### ISSUE THREAD

**Issue by blurpiflurp** [PowerAruba/PowerArubaSW#119]
Hi!

Just a note:
PS> get-arubaswpoe -connection $arubaswitch[0]
Get-ArubaSWPoE : A parameter cannot be found that matches parameter name 'connection'.

**Comment by blurpiflurp** [comment]
Hmm noticed now that it does, however the published version on psgallery doesn't have it (v 0.8.0)

**Comment by alagoutte** [comment]
Yes, i need to publish a new release...
