### ISSUE TITLE
hp 1820/1920 error Connect-ArubaSW

### ISSUE THREAD

**Issue by Shmreali** [PowerAruba/PowerArubaSW#132]
i have an old aruba switches 
**hp 1820
HPE 1920**
with the latest firmeware - HPE OfficeConnect Switch 1820 48G J9981A, **PT.02.11**
cant connect them in powershell "
**Connect-ArubaSW 192.168.2.238 -Username $username -Password $password #-SkipCertificateCheck** 

i get this error:

WARNING: The Switch API sends an error message:
WARNING: Error description (code): Not Found (404)
WARNING: Error details: 

Not Found

HTTP/1.1 404The requested resource is not available.
someone to  help ?

thanks

**Comment by alagoutte** [comment]
Hi @Shmreali 

Sorry but there is not APi on HPE OfficeConnect... you can't not use this module..
