### ISSUE TITLE
Updating Firmware

### ISSUE THREAD

**Issue by 2relativ** [PowerAruba/PowerArubaSW#134]
Hello everyone,

so it seems there is only a Get-Firmware funktion. What about Post? I was trying to upload it myself with invoke-restmethod but that seems slow and also runs into a timeout (tineout defined by the switch, it doesn't matter if I set the timeout in Powershell myself)
So I was wondering: Is there a plan to implement Post? Or is it simply not possible to speed up the connection?

**Comment by alagoutte** [comment]
hi @2relativ 

Good question... never try ! do you have using HTTP or HTTPS ?
What url do you are uisng ?

**Comment by 2relativ** [comment]
I am using https and the url is https://$Ipaddress/rest/$apiversion/firmware?image=primary

Or secondary or even both primary, secondary

**Comment by alagoutte** [comment]
> I am using https and the url is https://$Ipaddress/rest/$apiversion/firmware?image=primary
> 
> Or secondary or even both primary, secondary

What switch model ?!

**Comment by alagoutte** [comment]
> I am using https and the url is https://$Ipaddress/rest/$apiversion/firmware?image=primary
> 
> Or secondary or even both primary, secondary

I think you are using the wrong module, it is an API call for ArubaCX, you need to look [PowerArubaCX](https://github.com/PowerAruba/PowerArubaCX) module

**Comment by 2relativ** [comment]
Oh, sorry. No I am using the right repo. It is just that I reported the issue in the wrong one. Sorry, my bad!
