### ISSUE TITLE
Add support of multi release API

### ISSUE THREAD

**Issue by alagoutte** [PowerAruba/PowerArubaSW#70]
There is multiple API release following firmware, the project start with APIv4 (16.05.xxxx)

need to add a option to specify API when connect and when launch query

**Comment by alagoutte** [comment]
For example with 2930F with firmware 16.08(.0001)

```powershell
PS C:\Users\alagoutte> Get-ArubaSWRestVersion

version
-------
v1.0
v2.0
v2.1
v2.2
v3.0
v3.1
v4.0
v5.0
v6.0
```

**Comment by rddoove** [comment]
Will there be a 0.9 version?

**Comment by alagoutte** [comment]
Yes !

But I think there is not yet multi API for 0.9.0 but more RADIUS stuff (I
will work soon to merge PR)
